//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace SPWeb.localhost {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Data;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="SPWSSoap", Namespace="http://tempuri.org/SPWeb/")]
    public partial class SPWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback LoadRatesOperationCompleted;
        
        private System.Threading.SendOrPostCallback LoadTransactionsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SPWS() {
            this.Url = global::SPWeb.Properties.Settings.Default.SPWeb_localhost_SPWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event LoadRatesCompletedEventHandler LoadRatesCompleted;
        
        /// <remarks/>
        public event LoadTransactionsCompletedEventHandler LoadTransactionsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SPWeb/LoadRates", RequestNamespace="http://tempuri.org/SPWeb/", ResponseNamespace="http://tempuri.org/SPWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LoadRates(string currencyFrom, string currencyTo, string orderBy, string refreshFromWeb) {
            object[] results = this.Invoke("LoadRates", new object[] {
                        currencyFrom,
                        currencyTo,
                        orderBy,
                        refreshFromWeb});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoadRatesAsync(string currencyFrom, string currencyTo, string orderBy, string refreshFromWeb) {
            this.LoadRatesAsync(currencyFrom, currencyTo, orderBy, refreshFromWeb, null);
        }
        
        /// <remarks/>
        public void LoadRatesAsync(string currencyFrom, string currencyTo, string orderBy, string refreshFromWeb, object userState) {
            if ((this.LoadRatesOperationCompleted == null)) {
                this.LoadRatesOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadRatesOperationCompleted);
            }
            this.InvokeAsync("LoadRates", new object[] {
                        currencyFrom,
                        currencyTo,
                        orderBy,
                        refreshFromWeb}, this.LoadRatesOperationCompleted, userState);
        }
        
        private void OnLoadRatesOperationCompleted(object arg) {
            if ((this.LoadRatesCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadRatesCompleted(this, new LoadRatesCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SPWeb/LoadTransactions", RequestNamespace="http://tempuri.org/SPWeb/", ResponseNamespace="http://tempuri.org/SPWeb/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Data.DataTable LoadTransactions(string desiredCurrency, string desiredSKU, string justTotals, string orderByColumn, string refreshFromWeb) {
            object[] results = this.Invoke("LoadTransactions", new object[] {
                        desiredCurrency,
                        desiredSKU,
                        justTotals,
                        orderByColumn,
                        refreshFromWeb});
            return ((System.Data.DataTable)(results[0]));
        }
        
        /// <remarks/>
        public void LoadTransactionsAsync(string desiredCurrency, string desiredSKU, string justTotals, string orderByColumn, string refreshFromWeb) {
            this.LoadTransactionsAsync(desiredCurrency, desiredSKU, justTotals, orderByColumn, refreshFromWeb, null);
        }
        
        /// <remarks/>
        public void LoadTransactionsAsync(string desiredCurrency, string desiredSKU, string justTotals, string orderByColumn, string refreshFromWeb, object userState) {
            if ((this.LoadTransactionsOperationCompleted == null)) {
                this.LoadTransactionsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLoadTransactionsOperationCompleted);
            }
            this.InvokeAsync("LoadTransactions", new object[] {
                        desiredCurrency,
                        desiredSKU,
                        justTotals,
                        orderByColumn,
                        refreshFromWeb}, this.LoadTransactionsOperationCompleted, userState);
        }
        
        private void OnLoadTransactionsOperationCompleted(object arg) {
            if ((this.LoadTransactionsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LoadTransactionsCompleted(this, new LoadTransactionsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LoadRatesCompletedEventHandler(object sender, LoadRatesCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadRatesCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadRatesCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void LoadTransactionsCompletedEventHandler(object sender, LoadTransactionsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LoadTransactionsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LoadTransactionsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Data.DataTable Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Data.DataTable)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591